// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef balloon_h
#define balloon_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *prgwin;
#include <FL/Fl_Box.H>
#include <Fl/Fl_GIF_Image.H>
extern Fl_Box *background;
extern Fl_Box *mountain;
#include <FL/Fl_Button.H>
#include <iostream>
extern Fl_Button *blower1;
extern Fl_Button *blower2;
extern Fl_Button *blower3;
extern Fl_Button *blower4;
extern Fl_Button *blower5;
extern Fl_Box *flag1;
extern Fl_Box *balloon;
extern Fl_Box *flag2;
extern Fl_Button *restart;
extern Fl_Button *next;
extern Fl_Button *win;
extern Fl_Button *lose;
Fl_Double_Window* make_window();
#endif
